version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      go-dependencies:
        patterns: ["*"]
    commit-message:
      prefix: "build(deps)"
    labels: ["chore"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns: ["*"]
    commit-message:
      prefix: "ci(deps)"
    labels: ["chore"]
