name: Generate and Upload LeetCode Dataset

on:
  schedule:
    - cron: "0 0 * * 0" # Runs at 00:00 UTC every Sunday
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-dataset:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout generator repository
        uses: actions/checkout@v4
        with:
          repository: olegshulyakov/leetcode-dataset-generator
          path: generator

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"
          cache-dependency-path: generator/go.sum

      - name: Build Go application
        run: |
          cd generator
          go build -o leetcode-dataset

      - name: Checkout LeetCode repository
        uses: actions/checkout@v4
        with:
          repository: doocs/leetcode
          path: leetcode-repo

      - name: Generate dataset
        run: |
          ./generator/leetcode-dataset --repo=leetcode-repo --output=leetcode-solutions

      - name: Set up commit message
        id: commit-msg
        run: echo "msg=$(date +'Update %Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.0"
          cache: 'pip'

      - name: Install to Hugging Face CLI
        run: pip install huggingface_hub[cli]

      - name: Upload Dataset to Hugging Face
        run: hf upload --repo-type dataset --commit-message "${{ steps.commit-msg.outputs.msg }}" --token "${{ secrets.HF_TOKEN }}" "${{ secrets.HF_REPO_ID }}" "leetcode-solutions.parquet" "/default/train/0000.parquet"
